using Aoc2024Net.Tests.Attributes;
using NUnit.Framework;

namespace Aoc2024Net.Tests.Days
{
    [DayDataPart1(@"....#.....
                    .........#
                    ..........
                    ..#.......
                    .......#..
                    ..........
                    .#..^.....
                    ........#.
                    #.........
                    ......#...", 41)]
    [DayDataPart1(5199)]
    [DayDataPart2(@"....#.....
                    .........#
                    ..........
                    ..#.......
                    .......#..
                    ..........
                    .#..^.....
                    ........#.
                    #.........
                    ......#...", 6)]
    [DayDataPart2(1915)]
    [TestFixture]
    public sealed class Day6Tests : DayTests<Day6Tests>
    {
    }
}
