using Aoc2024Net.Tests.Attributes;
using NUnit.Framework;

namespace Aoc2024Net.Tests.Days
{
    [DayDataPart1(@"............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............", 14)]
    [DayDataPart1(357)]
    [DayDataPart2(@"............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............", 34)]
    [DayDataPart2(1266)]
    [TestFixture]
    public sealed class Day8Tests : DayTests<Day8Tests>
    {
    }
}
